/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TritonTransfer_CONSTANTS_H
#define TritonTransfer_CONSTANTS_H

#include "TritonTransfer_types.h"

namespace no { namespace podcasts { namespace no { namespace learning {

class TritonTransferConstants {
 public:
  TritonTransferConstants();

};

extern const TritonTransferConstants g_TritonTransfer_constants;

}}}} // namespace

#endif
