/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TritonTransfer_constants.h"

namespace no { namespace podcasts { namespace no { namespace learning {

const TritonTransferConstants g_TritonTransfer_constants;

TritonTransferConstants::TritonTransferConstants() {
}

}}}} // namespace

